export type character = {
    ac: number,
    currentHP: number,
    currentXp: number,
    id: number,
    lvl: number,
    maxHP: number,
    name: string,
    race: number,
    subRace: number,
    speed: number,
    stats: stats,
    skills: skills,
    // acrobatics: boolean,
    // animalHandling: boolean,
    // arcana: boolean,
    // athletics: boolean,
    // deception: boolean,
    // history: boolean,
    // insight: boolean,
    // intimidation: boolean,
    // investigation: boolean,
    // medicine: boolean,
    // nature: boolean,
    // perception: boolean,
    // performance: boolean,
    // persuasion: boolean,
    // religion: boolean,
    // sleightOfHand: boolean,
    // stealth: boolean,
    // survival: boolean,
    // charisma: number,
    // constitution: number,
    // dexterity: number,
    // intelligence: number,
    // strength: number,
    // wisdom: number,
    charismaProficiency:boolean,
    constitutionProficiency:boolean,
    dexterityProficiency:boolean,
    intelligenceProficiency:boolean,
    strengthProficiency:boolean,
    wisdomProficiency:boolean,
}

export type stats = {
    charisma: number,
    constitution: number,
    dexterity: number,
    intelligence: number,
    strength: number,
    wisdom: number
}

export type skills = {
    acrobatics: boolean,
    animalHandling: boolean,
    arcana: boolean,
    athletics: boolean,
    deception: boolean,
    history: boolean,
    insight: boolean,
    intimidation: boolean,
    investigation: boolean,
    medicine: boolean,
    nature: boolean,
    perception: boolean,
    performance: boolean,
    persuasion: boolean,
    religion: boolean,
    sleightOfHand: boolean,
    stealth: boolean,
    survival: boolean
}

